import JsonView from 'react18-json-view'
import hotelRooms from './data/rooms.json'
import { generateOccupancyData } from './utils/generateOccupancyData'
import './index.css'


function App() {
  return (
    <div className="p-8 flex flex-col gap-5">
      <h1 className="text-xl">React Developer Coding Challenge</h1>
      <div className="flex gap-x-10">
        <div className='w-1/2'>
          <p>Below you can see the data which you will find at ./data/rooms.json</p>
          <div className="bg-slate-700 p-4 rounded-xl mt-2">
            <JsonView src={hotelRooms} collapseStringsAfterLength={99} collapseObjectsAfterLength={20} />
          </div>
        </div>
        <div className='w-1/2'>
          <p>Here you can see the occupancy data that gets generated by a function at ./utils/generateOccupancyData.ts</p>
          <div className="bg-slate-700 p-4 rounded-xl mt-2">
            <JsonView src={generateOccupancyData()} collapseStringsAfterLength={99} collapseObjectsAfterLength={20} />
          </div>
        </div>
      </div>
    </div>
  )
}

export default App
